# Generated by Django 2.2.17 on 2020-12-13 09:04

import collections
from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('site_configuration', '0007_remove_values_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfiguration',
            name='site_values',
            field=jsonfield.fields.JSONField(blank=True, default=dict, load_kwargs={'object_pairs_hook': collections.OrderedDict}),
        ),
        migrations.AlterField(
            model_name='siteconfigurationhistory',
            name='site_values',
            field=jsonfield.fields.JSONField(blank=True, load_kwargs={'object_pairs_hook': collections.OrderedDict}),
        ),
    ]
